spring:
  application:
    name: problem-statement1 #Name of applicaton

logging:
  level:
    root: info
    assignments.kafka: info
  file: /var/tmp/apps/problem-statement1/problem-statement1 #Logging file path

kafka:
  kafkaProducer:
    #Kafka configuration changes according to the use cases
    bootstrap.servers: '172.17.5.36:7092' #Brokers
    acks: 'all'
    batch.size: 150000
    buffer.memory: 33554432
    client.id: 8
    retries: 1
    linger.ms: 10
    compression.type: 'lz4'
    key.serializer: 'org.apache.kafka.common.serialization.StringSerializer'
    value.serializer: 'assignments.kafka.common.serialization.StockTradeSerializer'

  metaData:
    topic: ps1-cap17 #Topic to send data

app:
  paths:
    filesDir: '/var/tmp/files1' #Directory containing data files