spring:
 application:
  name: problem-statement1

logging:
  level:    root: info
    assignments.kafka: debug  file: /var/log/apps/problem-statement1/problem-statement1

kafka:
  kafkaProducer:
    bootstrap.servers: '172.17.5.36:7092'
    acks: 'all'
    batch.size: 150000
    buffer.memory: 33554432
    client.id: 8
    retries: 1
    linger.ms: 10
    compression.type: 'lz4'
    key.serializer: 'org.apache.kafka.common.serialization.StringSerializer'
    value.serializer: 'assignments.kafka.common.serialization.StockTradeSerializer'

app:
  paths:
    filesDir: '/var/tmp/files'