spring:
  application:
    name: problem-statement2 #Name of application

logging:
  level:
    root: info
    assignments.kafka: debug
  file: /var/tmp/apps/problem-statement2/problem-statement2 #Logging file path

kafka:
  kafkaStreams:
    bootstrap.servers: '172.17.5.36:7092' #Brokers
    application.id: 'ps2'

  metaData:
    topic: ps1-cap4 #Topic to cosume data from
  
  #Producer to send aggregated data
  kafkaProducer:
    bootstrap.servers: '172.17.5.36:7092' #Brokers
    acks: 'all'
    #batch.size: 150000
    #buffer.memory: 33554432
    #client.id: 8
    #retries: 1
    #linger.ms: 10
    #compression.type: 'lz4'
    key.serializer: 'org.apache.kafka.common.serialization.StringSerializer'
    value.serializer: 'org.apache.kafka.common.serialization.DoubleSerializer'
